pkb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('', include('reports.urls', namespace='reports')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)


'''
urls.py (main):
www.example.com/path1/ - view
http://127.0.0.1:8000/test/


urls.py (app):
www.example.com/path1/ - view 1
http://127.0.0.1:8000/test/
www.example.com/path1/option1 - view 2
http://127.0.0.1:8000/test/sleep
www.example.com/path1/option2 - view 3
...

'''

reports/urls.py
from django.urls import path
from .views import (
    report_view, delete_view, ReportUpdateView, HomeView, SelectView, main_report_summary, get_generated_problems_in_pdf
)

app_name = 'reports'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('reports/', SelectView.as_view(), name="select-view"),
    path('reports/summary/', main_report_summary, name="summary-view"),
    path('reports/<str:dapatkan_laporan>/<pk>/update/',
         ReportUpdateView.as_view(), name="update-view"),
    path('reports/<str:dapatkan_laporan>/', report_view, name="report-view"),
    path('reports/delete/<pk>/', delete_view, name='delete-view'),
    path('reports/generate/pdf/', get_generated_problems_in_pdf, name='pdf'),
]

# /{{obj.dapatkan_laporan}}/{{obj.pk}}/update/

reports/models.py
import random
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from bantuan.models import JenisBantuan
from categories.models import Kategori
from areas.models import ProductionLine
from django.urls import reverse
from django.db.models import Sum, Avg
import random
from datetime import datetime




# Create your models here.

# hours= (
#     ("1", "1"),
#     ("2", "2"),
#     ("3", "3"),
#     ...
# )
#dapatkan report
hours = ([(str(x), str(x)) for x in range(1, 9)])

el = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
      'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

'''
get_queryset() - method responsible for retrieving all the data from the database according to
               the defined querysets
super()        -  method which returns a proxy object that allows you to refer parent class

def get_all_active(self):
    return super().get_queryset().filter(draft=False)
    return Post.objects.filter(draft=False)
'''


class ReportQueryset(models.QuerySet):
    def get_by_line_and_hari(self, hari, line_id):
        return self.filter(hari=hari, dapatkan_laporan__id=line_id)


class ReportManager(models.Manager):
    def get_queryset(self):
        return ReportQueryset(self.model, using=self._db)

    def get_by_line_and_hari(self, hari, line_id):
        return self.get_queryset().get_by_line_and_hari(hari, line_id)

class Report(models.Model):
    nama_sekolah = models.CharField(max_length=45, blank=True)
    kod_sekolah = models.CharField(max_length=7, blank= True)
    hari = models.DateField(default=timezone.now)
    hingga = models.DateField(default=timezone.now)
    waktu_mula = models.CharField(max_length=2, choices=hours)
    waktu_tamat = models.CharField(max_length=2, choices=hours)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    skop = models.ForeignKey(JenisBantuan, on_delete=models.CASCADE)
    dapatkan_laporan = models.ForeignKey(ProductionLine, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ReportManager()

    def get_hari(self):
        return self.hari.strftime('%Y/%m/%d')

    def get_absolute_url(self):
        return reverse("reports:update-view", kwargs={'dapatkan_laporan': self.dapatkan_laporan,'pk': self.pk, })

    def __str__(self):
        return "{}-{}-{}".format(self.waktu_mula, self.waktu_tamat, self.dapatkan_laporan, self.waktu_tamat, self.nama_sekolah, self.kod_sekolah)

    class Meta:
        ordering = ('-created',)


def random_code():
    random.shuffle(el)
    code = [str(x) for x in el[:12]]
    str_code = ''.join(code)

    return str_code


class ProblemReportedManager(models.Manager):
    def get_problems_by_hari_and_line(self, hari, line):
        return super().get_queryset().filter(report__hari=hari, report__dapatkan_laporan__name=line)

    def problems_from_today(self):
        now = datetime.now().strftime('%Y-%m-%d')
        return super().get_queryset().filter(report__hari=now)


class ProblemReported(models.Model):
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)
    isu  = models.TextField()
    problem_id = models.CharField(max_length=12, unique=True, blank=True, default=random_code)
    breakdown = models.PositiveIntegerField()
    umum = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    objects = ProblemReportedManager()

    def __str__(self):
        return "{}-{}".format(self.kategori.name, self.isu[:20])

    class Meta:
        verbose_name = "Report Masalah"
        verbose_name_plural = "Report Masalah"

reports/forms.py
from django import forms
from .models import Report, ProblemReported
from django.shortcuts import get_object_or_404
from areas.models import ProductionLine




class ReportResultForm(forms.Form):
    dapatkan_laporan = forms.ModelChoiceField(
        queryset=ProductionLine.objects.all())
    hari = forms.CharField(widget=forms.DateTimeInput(
        attrs={'class': 'datepicker'}
    ))


class ReportSelectLineForm(forms.Form):
    dapatkan_laporan = forms.ModelChoiceField(
        queryset=ProductionLine.objects.none(), label='')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        # print(user)
        super(ReportSelectLineForm, self).__init__(*args, **kwargs)
        self.fields['dapatkan_laporan'].queryset = ProductionLine.objects.filter(
            team_leader__user__username=user)


class ReportForm(forms.ModelForm):

    class Meta:
        model = Report
        # fields = '__all__'
        exclude = ('user', 'dapatkan_laporan',)

    def __init__(self, *args, **kwargs):
        dapatkan_laporan = kwargs.pop('dapatkan_laporan', None)
        super().__init__(*args, **kwargs)
        if dapatkan_laporan is not None:
            line = get_object_or_404(ProductionLine, name=dapatkan_laporan)
            # print(line.name)
            self.fields['skop'].queryset = line.products.all()


class ProblemReportedForm(forms.ModelForm):

    class Meta:
        model = ProblemReported
        # fields = '__all__'
        exclude = ('user', 'report', 'problem_id')

reports/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ReportForm, ProblemReportedForm, ReportSelectLineForm, ReportResultForm
from .models import Report, ProblemReported
from areas.models import ProductionLine
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView, FormView
from django.urls import reverse_lazy

from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


@login_required
def get_generated_problems_in_pdf(request):

    # queryset
    problems = ProblemReported.objects.problems_from_today()

    # context passed in the template
    context = {'problems': problems}

    # render
    html_string = render_to_string(
        'reports/problems.html', context)
    # html = HTML(string=html_string)
    html = HTML(string=html_string, base_url=request.build_absolute_uri())
    result = html.write_pdf()

    # http response
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'inline; filename=problem_list.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())

    return response


@login_required
def main_report_summary(request):
    try:
        hari = request.session.get('hari', None)
        prod_id = request.session.get('dapatkan_laporan', None)
        dapatkan_laporan = ProductionLine.objects.get(id=prod_id)
        problems = ProblemReported.objects.get_problems_by_hari_and_line(
            hari, dapatkan_laporan)
    except:
        return redirect('reports:select-view')

    context = {
        'problems_reported': problems,
        'hari': hari,
        'line': dapatkan_laporan,
    }

    del request.session['hari']
    del request.session['dapatkan_laporan']

    return render(request, 'reports/summary.html', context)


class SelectView(LoginRequiredMixin, FormView):
    template_name = 'reports/select.html'
    form_class = ReportResultForm
    success_url = reverse_lazy('reports:summary-view')

    def form_valid(self, form):
        self.request.session['hari'] = self.request.POST.get('hari', None)
        self.request.session['dapatkan_laporan'] = self.request.POST.get(
            'dapatkan_laporan', None)
        print(self.request.session['hari'])
        return super(SelectView, self).form_valid(form)


class HomeView(FormView):
    template_name = 'reports/home.html'
    form_class = ReportSelectLineForm

    def get_form_kwargs(self):
        kwargs = super(HomeView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def post(self, *args, **kwargs):
        prod_line = self.request.POST.get("prod_line")
        return redirect('reports:report-view', dapatkan_laporan=prod_line)


class ReportUpdateView(LoginRequiredMixin, UpdateView):
    model = Report
    form_class = ReportForm
    template_name = 'reports/update.html'

    def get_success_url(self):
        return self.request.path


@login_required
def delete_view(request, *args, **kwargs):
    r_id = kwargs.get("pk")
    obj = Report.objects.get(id=r_id)
    obj.delete()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def report_view(request, dapatkan_laporan):
    form = ReportForm(request.POST or None, dapatkan_laporan=dapatkan_laporan)
    pform = ProblemReportedForm(request.POST or None)
    queryset = Report.objects.filter(dapatkan_laporan__name=dapatkan_laporan)
    line = get_object_or_404(ProductionLine, name=dapatkan_laporan)

    if 'submitbtn1' in request.POST:
        r_id = request.POST.get("report_id")
        print(r_id)

        if pform.is_valid():
            report = Report.objects.get(id=r_id)
            print("data here")
            obj = pform.save(commit=False)
            obj.user = request.user
            obj.report = report
            obj.save()
            # form = ReportForm()
            # pform = ProblemReportedForm()
            return redirect(request.META.get('HTTP_REFERER'))

    elif 'submitbtn2' in request.POST:
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.dapatkan_laporan = line
            obj.save()
            # form = ReportForm()
            # pform = ProblemReportedForm()
            return redirect(request.META.get('HTTP_REFERER'))

    context = {
        'form': form,
        'pform': pform,
        'object_list': queryset,
    }

    return render(request, 'reports/report.html', context)

reports/templates/reports/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Utama {% endblock title %}

{% block content %}
<div class="col-6 mx-auto p-5">
    <div class="text-center text-white h1 mb-5">e-PKB</div>
        {% if request.user.is_authenticated %}
            <form action="" method="POST" class="form-control">
                <div class="text-muted h5 mb-2">Buat Pilihan Dibawah</div>
                {% csrf_token %}
                {{ form|crispy }}
                <input type="hidden" name="prod_line" id="prod_line">
                <button type="submit" class="btn btn-primary">Hantar</button>
            </form>
        {% else %}
            <div class="text-white text-center h3">Log Masuk Untuk Mula</div>
</div>

{% endif %}

<script>
$('#div_id_dapatkan_laporan').on("change", function() {
    const pl = $('#id_dapatkan_laporan option:selected').text()
    console.log(pl)
    $('#prod_line').val(pl)
});

</script>

{% endblock content %}

reports/templates/reports/problems.html
{% load static %}
<html>
<head>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:10px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:10px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-ve35{border-color:#c0c0c0;text-align:left;vertical-align:middle}
.tg .tg-wo29{border-color:#c0c0c0;text-align:left;vertical-align:top}
</style>
</head>

  <address><p>
    <p>KEMENTERIAN PENDIDIKAN MALAYSIA</p>
    <p>Pejabat Pendidikan daerah klang</p>
    <p>jalan Meru</p>
    <p>41050 Klang</p>
    <p>Selangor darul Ehsan</p>
  </p>
  <hr>
<p style="text-align:right;"</p>
Ruj Tuan  : <br>
Ruj Kami  : <b>PPD.ICT100-8/4()<br></b>
Tarikh    :{% for p in problems  %}
{{ p.created }}

</p>
<address>
<p>Pengetua/Guru Besar</p>
<p>Sekolah-sekolah Daerah klang</p>
<p>(Nama seperti lampiran)</p>
</address></p>
Tuan,

<article id="columns">
  <h3 id="columns-title">{{ p.kategori }}</h3>

<p>Dengan segala hormatnya saya merujuk kepada perkara di atas.
2.  Adalah dimaklumkan bahawa sekolah terlibat akan mengadakan Bengkel Khidmat Bantu(ICT) <b>( {{ p.problem_id}} )</b> pada ketetapan seperti berikut:
</p>
<p>Tarikh  : {{ p.created }}</p>
<p>Masa    : 8 Pagi - 5 Petang</p>
<p>Tempat  :</p>
<p>Peserta : Juruteknik Komputer / Pegawai Teknologi Maklumat</p>

<p>3.  Sehubungan dengan itu, mohon kerjasama pihak tuan untuk memaklumkan kepada Juruteknik Komputer / Penolong Pegawai Teknologi Maklumat Sekolah tuan menghadiri bengkel tersebut. Sebarang pertanyaan boleh berhubung dengan Mohd Fauzi bin Al-Kamal/Norsairi bin Ahmad Shahabudin/Latifah binti Noerfajar, melalui talian 03-3376 2879.
Segala kerjasama, perhatian dan sokongan yang tuan berikan dalam menjayakan bengkel ini didahului dengan ucapan ribuan terima kasih.
Sekian, terima kasih</p>
<b>"BERKHIDMAT UNTUK NEGARA"</b><br>
<br>
Sekian Terima Kasih.
</br>
Tandatangan tidak diperlukan, cetakan komputer

<br>
<br>
<br>
<br>

{% endfor %}

</html>

reports/templates/reports/report.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} report {% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="problemModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Report masalah</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="POST">
        {% csrf_token %}
        <div class="modal-body">
            {{pform|crispy}}
            <input type="hidden" name="report_id" id="report_id">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
            <button type="submit" name="submitbtn1" class="btn btn-primary">Hantar</button>
        </div>
       </form>
    </div>
  </div>
</div>

<div class="container bg-white shadow-lg rounded py-2">
    <div class="row">
        <div class="col-2">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy}}
                <button type="submit" name="submitbtn2" class="btn btn-primary w-100 shadow-sm mt-3"><i class="far fa-paper-plane pr-3"></i>Hantar</button>
            </form>
        </div>
        <div class="col-10">
            <div style="overflow-y:scroll; height:85vh" class="w-100 bg-light rounded border">
                <table class="table">
                    <thead class="thead-light">
                        <tr class="text-center">
                            <th scope="col">Hari</th>
                            <th scope="col">Mula</th>
                            <th scope="col">Tamat</th>
                            <th scope="col">Skop</th>
                            <th scope="col">Bahagian</th>
                            <th scope="col">Nama Sekolah</th>
                            <th scope="col"></th>
                            <th scope="col">Isu</th>
                            <th scope="col">Edit</th>
                            <th scope="col">Buang</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in object_list %}
                            <tr class="text-center">
                                <td>{{obj.get_hari}}</td>
                                <td>{{obj.waktu_mula}}</td>
                                <td>{{obj.waktu_tamat}}</td>
                                <td>{{obj.skop}}</td>
                                <td>{{obj.dapatkan_laporan}}</td>
                                <td>{{obj.nama_sekolah}}</td>
                                
                                <td>
                                    {% if obj.problemreported_set.all %}
                                        <div class="badge badge-danger">P</div>
                                    {% endif %}
                                </td>

                                <td class="fit">
                                    <button class="btn btn-warning open-modal" data-toggle="modal" data-target="#problemModal" data-url={{obj.id}}><i class="fas fa-exclamation-triangle"></i></button>
                                </td>
                                <td class="fit">
                                    <a href="{{obj.get_absolute_url}}"><button class="btn btn-info"><i class="far fa-edit"></i></button></a>
                                </td>
                                <td class="fit">
                                    <a href="{% url 'reports:delete-view' pk=obj.id %}"><button class="btn btn-danger"><i class="fas fa-trash-alt"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
$(".open-modal").on("click", function() {
    const r_id = $(this).attr("data-url")
    $("#report_id").val(r_id)
    console.log(r_id)
});

</script>

{% endblock content %}

reports/templates/reports/select.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Pilih Tarikh{% endblock title %}


{% block content %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
$(function(){
    $(".datepicker").datepicker({'dateFormat': 'yy-mm-dd'}).val()
});
</script>

<div class="col-6 mx-auto">
    <div class="text-white text-center h3 m-5">Pilihan dan tarikh </div>
    <form action="" method="POST" class="form-control" autocomplete="off">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Hantar</button>
    </form>
</div>



{% endblock content %}

reports/templates/reports/summary.html
{% extends 'base.html' %}
{% load oknok %}
{% load substract %}

{% block title %}rumusan{% endblock title %}

{% block content %}
<div class="container bg-white py-2 rounded">
    <div class="col-12">
        <div class="text-muted h2">
            <i class="fas fa-tachometer-alt mr-3"></i>Keputusan
        </div>
    </div>
    <div class="col">
        Analisis pada: <strong>{{ hari }} - {{ line }}</strong>
    </div>
    <br>
    <table class="table table-sm text-center">
        <thead>
            <tr>
                <th scope="col">Perbezaan</th>
                <th scope="col">OK ?</th>
            </tr>
        </thead>
        <tbody>
            <tr>

            </tr>
        </tbody>
    </table>
    <br>
    <h3>Isu - isu {masalah}</h3>
    <hr>
    {% for problem in problems_reported %}
    <small class="text-muted">{{ problem.problem_id }}</small><br>
    {{ problem.kategori }}<br>
    {{ problem.penerangan }}<br>
    {{ problem.breakdown}} min<br>

    <hr>
    {% endfor %}
</div>

{% endblock content %}

reports/templates/reports/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}kemaskini{% endblock title %}

{% block content %}

<div class="col-9 mx-auto">
    <div class="card p-4">
        <div class="text-muted mb-2 h4"> Buat Pilihan: {{ object.dapatkan_laporan }} </div>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Kemaskini</button>
        </form>
    </div>
</div>


{% endblock content %}