pkb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('', include('reports.urls', namespace='reports')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)


'''
urls.py (main):
www.example.com/path1/ - view
http://127.0.0.1:8000/test/


urls.py (app):
www.example.com/path1/ - view 1
http://127.0.0.1:8000/test/
www.example.com/path1/option1 - view 2
http://127.0.0.1:8000/test/sleep
www.example.com/path1/option2 - view 3
...

'''

posts/urls.py
from django.urls import path
from .views import PostCreateView, like_post, GeneralDetailPost, ProblemDetailPost, GeneralPostDelete

app_name = 'posts'

urlpatterns = [
    path('', PostCreateView.as_view(), name="post-list"),
    path('like/', like_post, name="post-like"),
    path('<pk>/detail/', GeneralDetailPost.as_view(), name='gp-detail'),
    path('<pk1>/<pk>/detail/', ProblemDetailPost.as_view(), name="pp-detail"),
    path('<pk>/delete/', GeneralPostDelete.as_view(), name="gp-delete"),
]

profiles/urls.py
from django.urls import path
from .views import profile_view

app_name = 'profiles'

urlpatterns = [
    path('', profile_view, name='profile-view'),
    # path('sleep/', test_view_1, name='test-view-1'),
    # path('view3/', test_view_2, name='test-view-2'),
]

reports/urls.py
from django.urls import path
from .views import (
    report_view, delete_view, ReportUpdateView, HomeView, SelectView, main_report_summary, get_generated_problems_in_pdf
)

app_name = 'reports'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('reports/', SelectView.as_view(), name="select-view"),
    path('reports/summary/', main_report_summary, name="summary-view"),
    path('reports/<str:dapatkan_laporan>/<pk>/update/',
         ReportUpdateView.as_view(), name="update-view"),
    path('reports/<str:dapatkan_laporan>/', report_view, name="report-view"),
    path('reports/delete/<pk>/', delete_view, name='delete-view'),
    path('reports/generate/pdf/', get_generated_problems_in_pdf, name='pdf'),
]

# /{{obj.dapatkan_laporan}}/{{obj.pk}}/update/

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--custom css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"
    <!--bootstrap css & js-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>

    <!--Fontawesome-->
    <script src="https://kit.fontawesome.com/6809eb288c.js"></script>


    <title>eTikeIT| {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <section class="bg-info" style="min-height:85vh">
        <div class="pt-big">
        {% block content %}
        {% endblock content %}
        </div>
    </section>
    {% include 'footer.html' %}
 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
  </body>
</html>

templates/footer.html
{% load static %}
<footer>
    <div class="col-12">
        <div class="row">
            <div class="col-8 p-5">
                Sistem ini dibangunkan untuk kegunaan sekolah bagi pemohonan Khidmat Bantu ICT berfokuskan kepada isu teknikal dan pembangunan Insfrastruktur ICT                
            </div>

            <div class="col-4 p-5">
                <div class="container h1 text-right">
                    <i class="fab fa-youtube ml-2"></i>

                </div>
                <div>
                    <img src='{% static 'award.png' %}' height=90 width='auto'>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 bg-white text-center p-2"><p>&copy; 2020 <p></div>
</footer>

templates/navbar.html
{% url 'profiles:profile-view' as path_profiles %}
{% url 'reports:home' as path_home %}
{% url 'posts:post-list' as path_board %}
{% url 'reports:select-view' as path_report %}

<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-info border-bottom border-secondary font-q fixed-top py-3">
    <div class="container">
        <a class="navbar-brand" href="{{ path_home }}">ePKB</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == path_home %}active{% endif %}">
                    <a class="nav-link" href="{% url 'reports:home' %}">Utama</a>
                </li>
                <li class="nav-item {% if request.path == path_board %}active{% endif %}">
                    <a class="nav-link" href="{% url 'posts:post-list' %}">Meja Bantuan</a>
                </li>
                <li class="nav-item {% if request.path == path_report %}active{% endif %}">
                    <a class="nav-link" href="{% url 'reports:select-view' %}">Dapatkan report</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:pdf' %}">PDF hari Ini</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.path == path_profiles %}active{% endif %}">
                        <a href="{% url 'profiles:profile-view' %}" class="nav-link">
                            <img src="{{ picture.url }}" class="img-avatar" alt="profile picture">
                            <span class="ml-2">{{request.user}}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">
                            <i class="fas fa-power-off mt-2"></i>
                        </a>
                    </li>
                {% else %}
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">
                            <i class="fa fa-sign-in-alt"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>